server {
    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    server_name a25albsanrom.daw.inspedralbes.cat;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/test-name/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/test-name/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/test-name/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    # Raíz global (debe coincidir con la carpeta public de Laravel en el contenedor de la API)
    root /var/www/public;
    index index.php;

    # 1. Backend API (Laravel)
    location /api {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Procesamiento de archivos PHP
    location ~ \.php$ {
        fastcgi_pass api:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        
        # Debugging headers (opcional)
        add_header X-Debug-Path $document_root$fastcgi_script_name;
    }

    # photos
    location /cartellera/ {
        autoindex on;
        alias /var/www/api/storage/app/public/cartellera/;
    }

    # 2. Websockets (Node.js)
    location /socket.io {
        proxy_pass http://websockets:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Frontend (Nuxt 3)
    # Importante: El front va al final como fallback
    location / {
        proxy_pass http://front:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
